Fixed file names to include directory.

diff --git a/process_files b/process_files
--- a/process_files
+++ b/process_files
@@ -18,20 +18,23 @@ fi
 
 fits_files=$dir/*.fit
 
-light_files=$(cat LIGHT_FILES.txt)
+light_files=$(cat $dir/LIGHT_FILES.txt)
 
-for file in $fits_files; do 
-    ./lat_long $file || exit 1;
+i=0
+for file in $fits_files; do
+    echo "Processing file $i of ${#fits_files}: $file"
+    ./lat_long  $file || exit 1;
     ./add_times $file || exit 1;
+    : $(( i++ ))
 done
 
 # Do any files need an object? If so, abort.
-if [[ -e NEEDS_OBJECT.txt ]]; then 
-    echo "Fix the object information before trying to add ra/dec!"
+if [[ -e $dir/NEEDS_OBJECT.txt ]]; then 
+    echo "ERROR: Fix the object information before trying to add ra/dec!"
     exit 1;
 fi
 
 for file in $light_files; do
-    ./ra_dec $file || exit 1
-    ./ha_airmass $file || exit 1
+    ./ra_dec $dir/$file || exit 1
+    ./ha_airmass $dir/$file || exit 1
 done
