Added -f option to force overwriting of keywords.

diff --git a/process_files b/process_files
--- a/process_files
+++ b/process_files
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+function show_help
+{
+    echo "Sure wish I had time to write documentation!"
+}
+
+while [[ $1 == -* ]]; do
+    case "$1" in
+      -h|--help|-\?) show_help; exit 0;;
+      -f ) force="-f"; shift;;
+      --) shift; break;;
+      -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
+    esac
+done
+
+if [[ $# != 1 ]] 
+then
+    show_help
+    exit 1
+fi
+
+#set -x
 dir=$1
 
 # check for wcstools
@@ -25,9 +46,9 @@ light_files=$(cat $dir/LIGHT_FILES.txt)
 #set -x
 i=0
 for file in $fits_files; do
-    echo "Processing file $i of $nfiles: $file"
-    ./lat_long  $file
-    ./add_times $file
+    echo "Processing file $(( i+1 )) of $nfiles: $file"
+    ./lat_long  $force $file
+    ./add_times $force $file
     : $(( i++ ))
 done
 
@@ -41,8 +62,8 @@ foo=( $light_files )
 nfiles=${#foo[@]}
 i=0
 for file in $light_files; do
-    echo "Processing file $i of $nfiles: $file"
-    ./ra_dec $dir/$file 
-    ./ha_airmass $dir/$file
+    echo "Processing file $(( i+1 )) of $nfiles: $file"
+    ./ra_dec $force $dir/$file 
+    ./ha_airmass $force $dir/$file
     : $(( i++ ))
 done
